version: "3.9"
services:
  traefik:
    image: traefik:v3.0
    command:
      - "--providers.docker=true"
      - "--providers.file.filename=/etc/traefik/dynamic.yml"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./infra/traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro"
    restart: unless-stopped

  whoami:
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.who.rule=Host(`localhost`) && PathPrefix(`/who`)"
      - "traefik.http.routers.who.entrypoints=web"
      - "traefik.http.services.who.loadbalancer.server.port=80"
  web:
    build: ./web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`localhost`)"
      - "traefik.http.routers.web.entrypoints=web"
      - "traefik.http.services.web.loadbalancer.server.port=80"
    restart: unless-stopped
networks:
  default:
    name: netto-net
