version: "3.9"

services:
  traefik:
    image: traefik:v3.0
    command:
      - "--providers.docker=true"
      - "--providers.file.filename=/etc/traefik/dynamic.yml"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--certificatesresolvers.le.acme.email=${LE_EMAIL}"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./infra/traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro"
      - "./infra/traefik/acme.json:/letsencrypt/acme.json"
    restart: unless-stopped

  web:
    build: ./web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=le"
      - "traefik.http.services.web.loadbalancer.server.port=80"
    restart: unless-stopped

  whoami:
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.who.rule=Host(`${DOMAIN}`) && PathPrefix(`/who`)"
      - "traefik.http.routers.who.entrypoints=websecure"
      - "traefik.http.routers.who.tls.certresolver=le"
      - "traefik.http.services.who.loadbalancer.server.port=80"
    restart: unless-stopped

networks:
  default:
    name: netto-net
